name: build AmazonCorrettoJava
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - Amazon-Corretto-java8/**
      - Amazon-Corretto-java11/**
      - Amazon-Corretto-java16/**
      - Amazon-Corretto-java17/**
jobs:
  push:
    name: "yolks:amazon-corretto-java${{ matrix.tag }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag:
          - '8'
          - '11'
          - '16'
          - '17'
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v2
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUBTOKEN }}
      - uses: docker/build-push-action@v3
        with:
          context: ./Amazon-Corretto-java${{ matrix.tag }}
          file: ./Amazon-Corretto-java${{ matrix.tag }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ghcr.io/neko7sora/yolks:amazon-corretto-java${{ matrix.tag }}
